import type { Product } from '../types'

export const products: Product[] = [
	{
		title: "Dentime",
		url: "https://dentime.anozon.me/",
		urlLive: true,
		description: "時間割時刻管理ツール",
		filename: "dentime.png",
		iconFilename: "icon-dentime.png",
		tags: ["PWA","React"],
		size: "L",
		hasImage: true,
	},
	{
		title: "苦手タイパー",
		url: "https://tools.anozon.me/nigate-typer",
		urlLive: false,
		description: "簡易単語タイピングツール",
		filename: "nigate-typer.png",
		tags: ["React"],
		size: "S",
		hasImage: false,
	},
	{
		title: "elzup.com",
		url: "https://elzup.com",
		urlLive: true,
		description: "大学時代の自分跡地",
		filename: "elzup.png",
		tags: ["React"],
		size: "M",
		hasImage: true,
	},
	{
		title: "nozctf",
		url: "https://nozctf.web.app",
		urlLive: true,
		description: "Firebase で作った web 問題 CTF サイト",
		filename: "nozctf.png",
		iconFilename: "icon-nozctf.png",
		tags: ["React","TypeScript"],
		size: "M",
		hasImage: true,
	},
	{
		title: "Scope Timer",
		url: "https://tools.anozon.me/scope-timer",
		urlLive: true,
		description: "ミリ秒精度の実験用タイマー",
		filename: "scope-timer.png",
		tags: ["React","TypeScript"],
		size: "M",
		hasImage: true,
	},
	{
		title: "Code Explorer",
		url: "https://tools.anozon.me/code-explorer",
		urlLive: true,
		description: "コード探索・解析ツール",
		filename: "code-explorer.png",
		iconFilename: "icon-code-explorer.png",
		tags: ["React","TypeScript"],
		size: "M",
		hasImage: true,
	},
	{
		title: "999",
		url: "https://anoz-memosupo.web.app/",
		urlLive: true,
		githubUrl: "https://github.com/elzup/999",
		description: "メモリースポーツ用 3桁数字変換表作成ツール",
		filename: "999.png",
		iconFilename: "icon-999.png",
		tags: ["TypeScript","React"],
		size: "M",
		hasImage: true,
		imageLayout: "split",
	},
	{
		title: "DesktopStickers",
		url: "",
		urlLive: false,
		githubUrl: "https://github.com/elzup/DesktopStickers",
		description: "好きな技術ロゴを並べたデスクトップ壁紙",
		filename: "desktopstickers.png",
		tags: ["JavaScript"],
		size: "S",
		hasImage: false,
	},
	{
		title: "曜日計算",
		url: "https://tools.anozon.me/weekday-calc",
		urlLive: true,
		description: "曜日計算アルゴリズムのステップ可視化",
		filename: "weekday-calc.png",
		tags: ["TypeScript","React"],
		size: "S",
		hasImage: true,
		imageLayout: "split",
	},
	{
		title: "Clipsh",
		url: "https://tools.anozon.me/clipsh",
		urlLive: false,
		description: "クリップボードエディタ",
		filename: "clipsh.png",
		iconFilename: "icon-clipsh.png",
		tags: ["React"],
		size: "M",
		hasImage: true,
	},
	{
		title: "Saikoron",
		url: "https://saikorone.web.app/",
		urlLive: false,
		description: "サイコロ作成・超汎用乱数ツール",
		filename: "saikoron.png",
		tags: [],
		size: "M",
		hasImage: true,
	},
	{
		title: "anozon.me",
		url: "https://anozon.me",
		urlLive: false,
		description: "プロフィールサイト",
		filename: "another-node.png",
		tags: ["React"],
		size: "M",
		hasImage: true,
	},
	{
		title: "blog.anozon.me",
		url: "https://blog.anozon.me/",
		urlLive: true,
		description: "GitHub Actions+Pages で運用しているブログ",
		filename: "anozonblog.png",
		tags: ["React","Gatsby"],
		size: "M",
		hasImage: true,
	},
	{
		title: "ピクブルMEMO",
		url: "https://tools.anozon.me/pikbl-memo",
		urlLive: true,
		description: "ピクミンブルーム苗管理アプリ",
		filename: "pikuburu-memo.png",
		iconFilename: "icon-pikuburu-memo.png",
		tags: ["PWA","React"],
		size: "M",
		hasImage: true,
		imageLayout: "split",
	},
	{
		title: "Mitelop",
		url: "https://mitelop.anozon.me/",
		urlLive: false,
		description: "配信ガジェット",
		filename: "mitelop.png",
		iconFilename: "icon-mitelop.png",
		tags: ["PWA","React","TypeScript"],
		size: "M",
		hasImage: true,
	},
	{
		title: "Googol",
		url: "https://tools.anozon.me/googol",
		urlLive: true,
		description: "10^100 歯車装置 3D ビジュアライザー",
		filename: "googol.png",
		tags: ["React","TypeScript","Three.js"],
		size: "M",
		hasImage: true,
	},
	{
		title: "リサージュ曲線",
		url: "https://tools.anozon.me/lissajous",
		urlLive: true,
		description: "リサージュ曲線グリッド可視化",
		filename: "lissajous.png",
		iconFilename: "icon-lissajous.png",
		tags: ["React","TypeScript"],
		size: "M",
		hasImage: true,
	},
	{
		title: "Daily Report",
		url: "",
		urlLive: false,
		description: "AI 日報ダッシュボード",
		filename: "daily-report-ai.png",
		tags: ["React","TypeScript"],
		size: "M",
		hasImage: false,
	},
	{
		title: "虫食い検索",
		url: "https://tools.anozon.me/mushikui-search",
		urlLive: true,
		description: "ワイルドカード単語検索",
		filename: "mushikui-search.png",
		tags: ["React","TypeScript"],
		size: "S",
		hasImage: false,
	},
	{
		title: "SpanBox",
		url: "https://tools.anozon.me/spanbox",
		urlLive: true,
		description: "グリッド上のブロック配置エディタ",
		filename: "spanbox.png",
		tags: ["React","TypeScript"],
		size: "M",
		hasImage: false,
	},
	{
		title: "シートベルト慣性ロック",
		url: "https://tools.anozon.me/seatbelt",
		urlLive: true,
		description: "シートベルト慣性ロック機構のシミュレーション",
		filename: "seatbelt.png",
		tags: ["React","TypeScript"],
		size: "S",
		hasImage: false,
	},
	{
		title: "無限チョコレートパズル",
		url: "https://tools.anozon.me/infinite-chocolate",
		urlLive: true,
		description: "無限チョコレートの錯視パズル",
		filename: "infinite-chocolate.png",
		tags: ["React","TypeScript"],
		size: "S",
		hasImage: false,
	},
	{
		title: "進行タイマー",
		url: "https://tools.anozon.me/progress-timer",
		urlLive: true,
		description: "タイムライン付き進行タイマー",
		filename: "progress-timer.png",
		tags: ["React","TypeScript"],
		size: "S",
		hasImage: false,
	},
	{
		title: "ストロボ効果",
		url: "https://tools.anozon.me/strobe",
		urlLive: true,
		description: "ストロボ点滅効果ビジュアライザー",
		filename: "strobe.png",
		tags: ["React","TypeScript"],
		size: "S",
		hasImage: false,
	},
	{
		title: "RGB 全組み合わせ",
		url: "https://tools.anozon.me/rgb-combo",
		urlLive: true,
		description: "RGB 全色組み合わせ可視化",
		filename: "rgb-combo.png",
		tags: ["React","TypeScript"],
		size: "S",
		hasImage: false,
	},
	{
		title: "ドミノ倒し",
		url: "https://tools.anozon.me/domino-3d",
		urlLive: true,
		description: "3D ドミノ倒しシミュレーション",
		filename: "domino-3d.png",
		tags: ["React","TypeScript","Three.js"],
		size: "M",
		hasImage: false,
	},
	{
		title: "スタミナ計算機",
		url: "https://tools.anozon.me/stamina-calc",
		urlLive: true,
		description: "ゲームのスタミナ回復時間計算機",
		filename: "stamina-calc.png",
		tags: ["React","TypeScript"],
		size: "S",
		hasImage: false,
	},
	{
		title: "Venn, Upset viewer",
		url: "https://tools.anozon.me/upset-viewer",
		urlLive: true,
		description: "集合の Venn・UpSet 図ビューア",
		filename: "upset-viewer.png",
		tags: ["React","TypeScript"],
		size: "M",
		hasImage: false,
	},
	{
		title: "Float有効桁数デモ",
		url: "https://tools.anozon.me/float-precision",
		urlLive: true,
		description: "浮動小数点の有効桁数デモ",
		filename: "float-precision.png",
		tags: ["React","TypeScript"],
		size: "S",
		hasImage: false,
	},
]
