import type { Product } from '../types'

export const products: Product[] = [
	{
		title: "Dentime",
		url: "https://dentime.anozon.me/",
		urlLive: true,
		description: "時間割時刻管理ツール",
		filename: "dentime.png",
		tags: ["PWA","React"],
		size: "L",
		hasImage: true,
	},
	{
		title: "苦手タイパー",
		url: "https://tools.anozon.me/nigate-typer",
		urlLive: false,
		description: "簡易単語タイピングツール",
		filename: "nigate-typer.png",
		tags: ["React"],
		size: "S",
		hasImage: false,
	},
	{
		title: "elzup.com",
		url: "https://elzup.com",
		urlLive: true,
		description: "大学時代の自分跡地",
		filename: "elzup.png",
		tags: ["React"],
		size: "M",
		hasImage: true,
	},
	{
		title: "nozctf",
		url: "https://nozctf.web.app",
		urlLive: true,
		description: "Firebase で作った web 問題 CTF サイト",
		filename: "nozctf.png",
		tags: ["React","TypeScript"],
		size: "M",
		hasImage: true,
	},
	{
		title: "Scope Timer",
		url: "https://tools.anozon.me/scope-timer",
		urlLive: true,
		description: "ミリ秒精度の実験用タイマー",
		filename: "scope-timer.png",
		tags: ["React","TypeScript"],
		size: "M",
		hasImage: true,
	},
	{
		title: "Code Explorer",
		url: "https://tools.anozon.me/code-explorer",
		urlLive: true,
		description: "コード探索・解析ツール",
		filename: "code-explorer.png",
		tags: ["React","TypeScript"],
		size: "L",
		hasImage: true,
	},
	{
		title: "Clipsh",
		url: "https://tools.anozon.me/clipsh",
		urlLive: false,
		description: "クリップボードエディタ",
		filename: "clipsh.png",
		tags: ["React"],
		size: "M",
		hasImage: true,
	},
	{
		title: "Saikoron",
		url: "https://saikorone.web.app/",
		urlLive: false,
		description: "サイコロ作成・超汎用乱数ツール",
		filename: "saikoron.png",
		tags: [],
		size: "M",
		hasImage: false,
	},
	{
		title: "anozon.me",
		url: "https://anozon.me",
		urlLive: false,
		description: "プロフィールサイト",
		filename: "another-node.png",
		tags: ["React"],
		size: "M",
		hasImage: true,
	},
	{
		title: "blog.anozon.me",
		url: "https://blog.anozon.me/",
		urlLive: true,
		description: "GitHub Actions+Pages で運用しているブログ",
		filename: "anozonblog.png",
		tags: ["React","Gatsby"],
		size: "L",
		hasImage: true,
	},
	{
		title: "ピクブルMEMO",
		url: "https://tools.anozon.me/pikuburu-memo",
		urlLive: false,
		description: "ピクミンブルーム苗管理アプリ",
		filename: "pikuburu-memo.png",
		tags: ["PWA","React"],
		size: "M",
		hasImage: true,
	},
	{
		title: "Mitelop",
		url: "https://mitelop.anozon.me/",
		urlLive: false,
		description: "配信ガジェット",
		filename: "mitelop.png",
		tags: ["PWA","React","TypeScript"],
		size: "L",
		hasImage: true,
	},
]
